"""add submission table

Revision ID: fa0fd508c36f
Revises: 5ccef108b5f0
Create Date: 2026-06-04 00:06:39.220395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fa0fd508c36f'
down_revision: Union[str, Sequence[str], None] = '5ccef108b5f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Manage the native PG enum type explicitly with create_type=False so creation
# and destruction are symmetric: op.create_table does NOT auto-create it, and
# downgrade can drop it. (Inline sa.Enum auto-creates on upgrade but never drops
# on drop_table, leaving an orphan type that breaks re-upgrade.)
submission_status = postgresql.ENUM(
    'pending', 'accepted', 'wrong_answer', 'runtime_error', 'compile_error',
    'time_limit_exceeded', 'memory_limit_exceeded', 'internal_error',
    name='submissionstatus',
    create_type=False,
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    submission_status.create(op.get_bind(), checkfirst=True)
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('problem_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', submission_status, server_default='pending', nullable=False),
    sa.Column('judge0_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stdout', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stderr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('compile_output', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('runtime_ms', sa.Integer(), nullable=True),
    sa.Column('memory_kb', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problem.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_submission_created_at', 'submission', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('ix_submission_idempotency_key'), 'submission', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_submission_problem_id'), 'submission', ['problem_id'], unique=False)
    op.create_index(op.f('ix_submission_user_id'), 'submission', ['user_id'], unique=False)
    op.create_index('ix_submission_user_idempotency', 'submission', ['user_id', 'idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_submission_user_idempotency', table_name='submission', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_index(op.f('ix_submission_user_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_problem_id'), table_name='submission')
    op.drop_index(op.f('ix_submission_idempotency_key'), table_name='submission')
    op.drop_index('ix_submission_created_at', table_name='submission')
    op.drop_table('submission')
    submission_status.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
