name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/prepvault
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0  # v7.0.0
      - name: Log into GHCR
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee  # v4.2.0
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and tag docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
      - name: Push docker image to GHCR
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}