name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/prepvault
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
      - name: Log into GHCR
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0  # v4.4.0
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and tag docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }} .
      - name: Push docker image to GHCR
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_sha }}