name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    permissions:
        contents: read
        packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/prepvault
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Log into GHCR
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and tag docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ github.sha }} .
      - name: Push docker image to GHCR
        run: docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}